import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CommandSearch from "./components/CommandSearch";
import { getFighters } from "./lib/fighters";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The app is auth-aware and backed by a live API, so render every route at
// request time. This also means `next build` never calls the backend (which
// isn't running during the Docker image build).
export const dynamic = "force-dynamic";

// Applies the saved theme to <html> before first paint to avoid a flash:
// localStorage (set by the toggle) -> the `theme` cookie (set on login from the
// user's saved preference) -> the OS preference. Runs synchronously in <head>.
const THEME_SCRIPT = `(function(){try{var d=document.documentElement,t=null;try{t=localStorage.getItem('theme')}catch(e){}if(!t){var m=document.cookie.match(/(?:^|;\\s*)theme=(dark|light)/);if(m)t=m[1]}if(!t){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}d.classList.toggle('dark',t==='dark')}catch(e){}})();`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Loaded once for the app-wide ⌘K search; cached briefly by getFighters().
  const fighters = await getFighters();
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <CommandSearch fighters={fighters} />
        {children}
      </body>
    </html>
  );
}
